### PR TITLE
Edited to include beam gains from observing log

### PR DESCRIPTION
**Pull request by rfriesen**
Includes default argument for future observing runs

### CODE REVIEW

**Comment by jpinedaf** [comment]
This solution assumes that we always will have a value for the beam gains, is it possible to have a default option of using beam gains =['1,1,1,1,1...,1'] ? Just to make sure that we can fall back to that option for the next observing session. 

What do you think @rfriesen @low-sky ?

**Comment by rfriesen** [comment]
Right, I guess I can put the default in the if statement, the same as Special Raw Dir - I put it as a default value in doPipeline but I see it would never get there. Will edit.

**Comment by jpinedaf** [comment]
Sure, I think the if statement would be perfect, and changing the default value in the function calling to 'None' would be also needed.

**Comment by rfriesen** [comment]
Ugh, then we're doing two if statements, though. I'm sure there's a more 
elegant way to do it..

**Pull request closed without merging**
